### PR TITLE
PHP 8 Support

### PR DESCRIPTION
**Pull request by blankse**

### CODE REVIEW

**Comment by jkphl** [comment]
Same here, trying to get this merged on the weekend

**Comment by blankse** [comment]
Dependency "clue/graph-composer" doesn't seem ready for 8.0 :(

**Comment by jkphl** [comment]
@blankse Unfortunately, simply removing clue/graph-composer is not an option for me. Need to get that PHP8 ready first.

**Comment by blankse** [comment]
@jkphl With the original clue/graph-composer it can be installed. Is this enough?

**Comment by jkphl** [comment]
@blankse Great news — that's a good start, yes. However, the one feature I added was the ability to skip development dependencies (or to only list development dependencies), as far as I remember. See https://github.com/clue/graph-composer/commit/28466d158dc678b946c757be129526cbf05ad3d7 and https://github.com/clue/graph-composer/commit/dff4bac16484fa429d6157e89118e922264323b5. We'd have to re-implement these features in order to move forward. Unfortunately, I won't have the capacity to do that anytime soon. Would you be able to step in here?

**Comment by rvanlaak** [comment]
If I'm correct `clue/graph-composer` is not a runtime dependency, but a "tool dependency" ?

Can we find a way to exclude this dependency from being a requirement for using `micrometa` in runtime? e.g. by running the `clue/graph-composer` via a Makefile task?

**Comment by blankse** [comment]
I merged the original repository in your fork. See https://github.com/jkphl/graph-composer/pull/1
When you can merge this. I can change it back to your fork.

**Review by rvanlaak — APPROVED** [review]

**Comment by blankse** [comment]
Ping @jkphl

**Comment by blankse** [comment]
@rvanlaak Can you create a release tag with this change?

**Comment by rvanlaak** [comment]
`v3.1.0` just has been released

**Comment by blankse** [comment]
@rvanlaak Thank you 👍🏼

**Pull request merged**
